import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
        <div className="fixed bottom-4 w-full text-center z-50 pointer-events-none mix-blend-difference">
          <div className="flex flex-col gap-1 items-center justify-center">
            <p className="text-[10px] uppercase tracking-widest text-white/20 font-mono">
              Website by Nieraj S
            </p>
            <p className="text-[8px] uppercase tracking-wider text-white/15 font-mono">
              Team: Kavishnu G | Likhith sai N
            </p>
          </div>
        </div>
      </body>
    </html>
  );
}
